leopard-js/leopard

scratch-js/Renderer.js, scratch-js/Sprite.js
This is fun! The touching block just made some serious performance gains.
Previously, in the "platform physics" demo, a single frame could take upwards of `60ms` when walking uphill. Now, the worst-case scenario takes about `11ms` to complete (on my machine). That's an 82% improvement!
The new version implements a lot of ideas from the [phosphorous source code](https://github.com/nathan/phosphorus/blob/915ecc1185654e7bb3279faa3ec3457852064088/phosphorus.js#L1641-L1680). Thanks @nathan! Especially useful was the `source-in` [composite operation](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation). It allows comparing alpha values without doing any extra math.
=> Massive performance improvements to touching block

scratch-js/Project.mjs
Previously, `_startTriggers` would add every new trigger to `Project.runningTriggers`, even if some of those triggers were already there. This would cause the same script to be executed multiple times in parallel with itself, causing weird stuff to happen.
Resolves #24.
=> In _startTriggers, only add triggers to runningTriggers if they're not already there

scratch-js/Color.mjs, scratch-js/Renderer.mjs, scratch-js/renderer/PenSkin.mjs, scratch-js/renderer/VectorSkin.mjs
- Only set pen uniforms if they need to be set
- This should improve pen performance a fair bit. I'm still looking into other ways to improve it but this is a good start.
- Optimize `Color.toRGBA[Normalized]` by not using the `Color`'s getter properties
- Prevent an `IndexSizeError` in `VectorSkin` by not trying to draw an SVG if its size is 0
=> Optimize pen line drawing + other WebGL improvements

scratch-js/Sprite.mjs
This must be merged before PullJosh/sb-edit#12.
It's a little silly that we need to add a new property only for these obscure blocks, but at least this is the only case of that being necessary - we *do* need to store that global value somewhere (perfect for the stage), and all the other blocks to be added are just no-ops.
=> Add counter property to stage, defaulting to zero

scratch-js/Costume.mjs, scratch-js/Renderer.mjs, scratch-js/renderer/SkinCache.mjs
- Return early if a skin's texture doesn't exist
- This prevents WebGL warnings from spamming the console.
- Handle double-resolution costumes
- I've moved the code for telling whether a costume is a bitmap costume to the `Costume` class. Costumes also now have a `resolution` property which is 2 for bitmaps and 1 for vectors. This matches Scratch 3.0, in which all bitmap costumes are double-resolution (single-resolution ones are upscaled during importing).
- Fix costume rotation centers' y-axes
- These were flipped. Turns out, they're not in "Scratch-space".
=> Renderer fixes

scratch-js/Input.mjs
E.g. "up arrow" instead of just "up". This will make projects which use arrow key inputs (e.g. "key pressed?" or "when key pressed") respond to arrow keys correctly.
Should be merged alongside PullJosh/sb-edit#20.
=> Add "arrow" to arrow-key names for key triggers to match sb3 output

LICENSE.txt, package.json
`package.json` already stated scratch-js was licensed under MIT; this PR adds an actual license file so that we 1) state specific copyrights (equal to code contributors, sorted oldest-contribution at top) and 2) have any legal bearings, as a result. It's also just good code practice, of course! :P
=> Add MIT license text, and me to contributors

scratch-js/Sprite.mjs
When accessing an array, we want a 0-indexed value, not 1-indexed.
(This code was copied from the costume-switching code; that code expects a 1-indexed value, so, without testing, it was carried over here. Sorry!)
Test it out with this project: https://scratch.mit.edu/projects/360176981/
=> Fix getting sound by index

scratch-js/Sound.mjs, scratch-js/Sprite.mjs, scratch-js/lib/decode-adpcm-audio.mjs
This PR implements ADPCM audio (sounds based on WAV files), completing support for playing sounds from imported Scratch projects.
Things of note:
- We reuse a single audio context for all sounds; it's stored on the `Sound` constructor itself. (It could be put in a variable local to that module, but I figured I'd expose the value just in case we want to reference it outside of that file later.)
- The ADPCM decoder is [a library file](https://github.com/adroitwhiz/bismuth/blob/master/src/bismuth/io/decode-adpcm-audio.js) taken from @adroitwhiz's Bismuth project. It's been slightly tweaked here to match our code style and export a few extra utility functions. I've included Bismuth's [LICENSE](https://github.com/adroitwhiz/bismuth/blob/master/LICENSE) in the header of that file, crediting …
=> Support ADPCM audio

scratch-js/Project.mjs, scratch-js/Sound.mjs, scratch-js/Sprite.mjs, scratch-js/lib/decode-adpcm-audio.mjs
**This PR is based on #52.**
View https://github.com/towerofnix/scratch-js/compare/adpcm-audio...audio-effects for a diff between the two branches.
This pull request adds support for audio effects to scratch-js, matching Scratch 3.0's behavior to the best of my research.
The big addition is a new `EffectChain` class (an additional export from the `Sound.mjs` file). It's used to keep track of and apply any audio effects. Effect descriptors (defined at the end of that file) tell exactly how effects should behave, providing code which either creates and modifies its own WebAudio nodes or interacts with individual Sound objects through their APIs to apply an effect.
An EffectChain acts independently of its container and the WebAudio output; it's up to the container to build connections …
=> Implement audio effects

package.json
It appears that `scratch-js/index.css`, added as part of the ask/answer implementation, is causing ESLint to fail--it is trying to lint it. This PR ensures that ESLint is only run on `.mjs` files.
=> Only lint .mjs files

scratch-js/Renderer.mjs
Resolves #61
`_updateStageSize` checks if `_currentFramebuffer` is `null` (meaning we're drawing to the displayed canvas itself instead of a framebuffer), but `_setFramebuffer` was setting `_currentFramebuffer` *after* calling `_updateStageSize`, breaking this check.
This PR ensures that `_updateStageSize` is called *after* `_currentFramebuffer` is properly set.
=> Set _currentFramebuffer before calling _updateStageSize()

src/Renderer.js, src/Sprite.js, src/renderer/ShaderManager.js, src/renderer/effectInfo.js
Resolves #65
This includes a lot of other code cleanups for the renderer that make this a lot easier to implement.
=>  Ignore ghost effect in "touching" tests

src/Renderer.js, src/renderer/PenSkin.js, src/renderer/ShaderManager.js, src/renderer/Shaders.js
This includes #88 because it touches some of the same code.
See the commit message for details on why I'm doing this--essentially, passing parameters (uniforms and attributes) into a shader requires knowing their location (numeric), and for ease of use, we map their names to those locations. Because we only do this mapping once, a `Map` (optimized for adding/removing elements often) is probably not the best choice.
I also commented `ShaderManager` a bit more so it's a tiny bit easier to understand--at some point, I want to go back and document the renderer code more.
=> Make shader attribute/uniform locations accessible via object properties

src/renderer/PenSkin.js, src/renderer/Shaders.js
This code is a bit ugly, but necessary to work around really bad floating-point precision in some mobile GPUs.
This was taken from scratch-render, but given that it's entirely my code, I don't expect any licensing issues.
=> Update pen line code to that used in scratch-render

src/Renderer.js
This seems to be an oversight--I was previously returning `undefined` if both sprites in a "touching" test were completely offscreen. Now it returns `false` as it should.
=> Return false if sprite collision is offscreen

src/Project.js, src/Sprite.js, src/Trigger.js
Resolves part of #122.
This PR adds support for "edge-activated" triggers, so named because they evaluate a predicate every step (e.g. "is the timer greater than N?") and trigger their script on the rising edge (when the predicate changes from `false` to `true`).
Trigger predicates/options can now be functions (which are passed the current target) as well as values. This is necessary because the input to a "greater than" block is actually droppable and can contain arbitrary scripts. For codegen purposes, it may be easier to have the function take *no* arguments and just bind the `this` value to the current target, but that seems jankier.
=> Add support for "when timer greater than"

src/Loudness.js, src/Project.js, src/Sprite.js, src/Trigger.js
Based on @apple502j's work, with some refactoring and rebasing to work with the new edge-activated trigger code and also clean up the code a bit.
Resolves #122 and closes #60.
=> Add support for the "loudness" block and "loudness greater than" trigger

example-project/Giga/Giga.js, example-project/Gobo/Gobo.js, src/Sprite.js, src/Trigger.js
This adds support for "when backdrop switches to" block. (example project uses it!) This also changes costume setter to check the sprite type (stage/normal sprite) so that you can't use `next costume` in stage, and removes `random costume` because it's not used in scratch-vm.
=> Add support for when backdrop switches to block

src/Watcher.js
Support for leopard-js/sb-edit#90. This is needed to pass min/max values from deserialized projects (sb3) to Leopard. The actual implementation for min/max is already implemented, and `step` is already passed through the constructor.
=> Take min/max in slider Watcher constructor

src/Sprite.js
Follow-up to #157, supports leopard-js/sb-edit#90. These too are needed for comprehensive Scratch compatibility. (`toString` technically isn't, but it's cleaner to use consistent casting methods.)
=> Compat support: toNumber, toString, string/array ops

package.json
Resolves #191
Just adds the `"types"` field to the `package.json` so that the types get exposed to people using the library.
~~Not tested yet, but should work~~
Tested and works.
=> Add `"types"` field to package.json

src/Renderer.ts
Resolves #205.
Instead of calling renderLayers, which will not render hidden sprites, call renderSprite directly. In addition, "touching mouse" should not early-return false if the sprite is hidden.
=> Fix stamp and "touching mouse" for hidden sprites

package.json, src/Project.ts, src/Renderer.ts, src/Sprite.ts, src/Watcher.ts, src/renderer/Drawable.ts, src/renderer/ShaderManager.ts, src/renderer/Skin.ts
Most of these seem to be from the "if on edge, bounce" PR.
In the future, we should consider setting up some CI for pull requests that lints and typechecks them automatically.
=> Fix lints and typechecking errors
